Added github button
MelkeyOSS/astrostation pull request #239
Opened 2023-03-21 00:46 UTC by madeleine-patience

2023-03-22 15:24 UTC, Melkeydev commented
@madeleine-patience Can you make this commit against staging instead of GH?
+ add yourself to the contributors file too!

2023-03-22 15:25 UTC, Melkeydev requested changes
Few nits

2023-03-23 02:22 UTC, royanger requested changes

2023-03-23 02:23 UTC, madeleine-patience commented on src/components/Nav/BottomButtons.tsx
> +            Github Repo
Text deleted, only icon present.

2023-03-23 02:23 UTC, madeleine-patience commented
> @madeleine-patience Can you make this commit against staging instead of GH?
> 
> * add yourself to the contributors file too!

Both of these are done.

2023-03-23 02:24 UTC, royanger approved these changes

2023-03-24 01:11 UTC, Melkeydev commented
![image](https://user-images.githubusercontent.com/53410236/227398971-3213bc4b-40f9-4291-9516-83e323fd5a2b.png)
The image seems to be a bit small.
the padding of the button is taking more of the attention than the actual GH logo.
Can we increase the size of the GH icon so it fills in more of the real-estate?

2023-03-24 06:26 UTC, madeleine-patience commented
Thank you for the comments, I've updated as you requested, PTAL

2023-03-24 16:49 UTC, madeleine-patience commented
I just had a second look this morning- maybe the buttons should be square.

2023-03-26 00:45 UTC, Hacksore commented on src/components/Nav/BottomButtons.tsx
> +window.open("https://github.com/MelkeyOSS/astrostation")
Hey here is a suggestion, using a `<a>` tag is going to be much better as a semantic HTML element.

So you would need to remove the `navigateToGithub()` function and make the button below use an anchor (`<a>`) tag.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

2023-03-26 00:51 UTC, royanger commented
Hey @madeleine-patience, we noticed that the new component that holds the bottom buttons is missing some left padding. The Donate button is butting up against the edge of the screen. Compare that to the production release to see the difference.

2023-03-27 03:10 UTC, madeleine-patience commented
@royanger padding re-added and @Hacksore I changed the navigate function to an anchor tag instead.

2023-03-28 04:58 UTC, merged