Task track patch
MelkeyOSS/astrostation pull request #255
Opened 2023-03-28 06:06 UTC by justnat3

By tracking a task, you could no longer not track it without resorting to a double-click. 

Untrack is now in place for a task that is already being tracked.

2023-03-28 06:19 UTC, justnat3 commented
linked to https://github.com/MelkeyOSS/astrostation/issues/254

2023-03-30 05:28 UTC, royanger requested changes

2023-03-30 05:28 UTC, royanger commented on src/components/TaskTracker/Task.tsx
> +      // @ts-ignore
Can we get rid of the TS error here?

2023-03-30 12:33 UTC, justnat3 commented on src/components/TaskTracker/Task.tsx
> +      // @ts-ignore
No problem, I will get that tonight

2023-03-30 13:32 UTC, justnat3 commented
please test this to see if you find the behavior is still not what we want it to be. I guess I didn't get it reproduce when I originally submitted the PR. So we just pass inProgress by flag now, seems like the way to go. Matches some of the other state management that this point anyways. 

Cheers, -Nate

2023-04-04 03:48 UTC, Melkeydev approved these changes
Tested and LGTM!

2023-04-04 03:49 UTC, merged